---
name: Codespell

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: '*.pdf'
          ignore_words_list: assertIn
