LTKCPP-- LLRP Toolkit C Plus Plus Library: Core LTK Library classes and functions
Core LTK Library classes and functions
Classes
class LLRP::CErrorDetails
Class to return error details in LTKCPP operations.
class LLRP::CTypeRegistry
A collection of pointers to CTypeDescriptors.
class LLRP::CElement
This is the base class for all parameter and message types.
class LLRP::CMessage
Base Class for All LLRP LTK Messages.
class LLRP::CParameter
Base Class for All LLRP LTK Parameters.
class LLRP::CDecoder
LTK LLRP Decoder class.
class LLRP::CEncoder
LTK LLRP Encoder class.
class LLRP::CConnection
LLRP connection class.
Functions
void enrollImpinjTypesIntoRegistry (CTypeRegistry *pTypeRegistry)
Enrolls the types for Impinj into the LTKCPP registry.
void enrollCoreTypesIntoRegistry (CTypeRegistry *pTypeRegistry)
Enrolls the types for Core into the LTKCPP registry.
Detailed Description
Function Documentation
enrollCoreTypesIntoRegistry()
void enrollCoreTypesIntoRegistry (CTypeRegistry * pTypeRegistry)
Enrolls the types for Core into the LTKCPP registry.
LTKCPP needs an internal registry for storing all the type information. This function is required to enroll the types for the Core into the operating registry.
For example – in order to decode and encode packets from the core LLRP specification The user must EnrollCoreTypesIntoRegistry.
Referenced by CC1G2BlockWriteOpSpecResult::setNumWordsWritten().
enrollImpinjTypesIntoRegistry()
void enrollImpinjTypesIntoRegistry (CTypeRegistry * pTypeRegistry)
Enrolls the types for Impinj into the LTKCPP registry.
LTKCPP needs an internal registry for storing all the type information. This function is required to enroll the types for the Impinj into the operating registry.
For example – in order to decode and encode packets from the core LLRP specification The user must EnrollCoreTypesIntoRegistry.
Referenced by CImpinjEnhancedIntegraReport::countCustom(), and usage().